# Generated by Django 5.2.3 on 2025-07-07 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("job_management", "0002_application"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("e_title", models.CharField(max_length=255)),
                ("e_start_time", models.DateTimeField()),
                ("e_duration", models.IntegerField()),
                ("e_submitted_at", models.DateTimeField()),
                ("e_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("e_status", models.CharField(max_length=255)),
                ("e_notes", models.TextField(blank=True, null=True)),
                ("create_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "a_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_management.application",
                    ),
                ),
            ],
            options={
                "db_table": "exam",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ExamObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("o_distraction_level", models.IntegerField(default=0)),
                ("o_noise_detected", models.BooleanField(default=0)),
                ("o_tab_switches", models.IntegerField(default=0)),
                (
                    "o_eye_contact_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "o_suspesious_behaviour",
                    models.TextField(blank=True, default=0, null=True),
                ),
                ("o_dressing_code_ok", models.BooleanField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "e",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination_management.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exam_observation",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q_text", models.TextField()),
                ("q_choices", models.TextField()),
                ("q_correct_answer", models.TextField()),
                ("q_ai_generated", models.BooleanField()),
                ("q_score_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("q_type", models.TextField()),
                (
                    "e",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination_management.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exam_question",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_text", models.TextField()),
                (
                    "a_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("a_review_notes", models.TextField(blank=True, null=True)),
                ("create_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "q",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination_management.examquestion",
                    ),
                ),
            ],
            options={
                "db_table": "exam_answer",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("i_scheduled_at", models.DateTimeField()),
                ("i_status", models.CharField(blank=True, max_length=255, null=True)),
                ("i_notes", models.TextField(blank=True, null=True)),
                ("i_feedback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "a_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_management.application",
                    ),
                ),
                (
                    "u_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "interview",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InterviewObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "o_punctuality_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("o_dressing_code_ok", models.BooleanField()),
                ("o_gestures_detected", models.TextField()),
                ("o_face_expressions", models.TextField()),
                ("o_communitication_clarity", models.IntegerField()),
                (
                    "o_professionalism_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "i",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="examination_management.interview",
                    ),
                ),
            ],
            options={
                "db_table": "interview_observation",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q_text", models.TextField()),
                ("q_choices", models.TextField()),
                ("q_correct_answer", models.TextField()),
                ("q_ai_generated", models.BooleanField()),
                ("q_score_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("q_type", models.TextField()),
                (
                    "i",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination_management.interview",
                    ),
                ),
            ],
            options={
                "db_table": "interview_question",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InterviewResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r_text", models.TextField()),
                (
                    "r_socre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("r_review_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "q",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination_management.interviewquestion",
                    ),
                ),
            ],
            options={
                "db_table": "interview_response",
                "managed": True,
            },
        ),
    ]
