# Generated by Django 5.2.3 on 2025-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="e_deadline_type",
            field=models.CharField(default="fixed", max_length=255),
        ),
        migrations.AddField(
            model_name="exam",
            name="e_type",
            field=models.CharField(default="written", max_length=255),
        ),
        migrations.AlterField(
            model_name="exam",
            name="e_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="e_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
