# Generated by Django 5.2.3 on 2025-09-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0002_exam_e_deadline_type_exam_e_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="e_max_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="exam",
            name="e_mode",
            field=models.CharField(default="online", max_length=255),
        ),
    ]
