# Generated by Django 5.2.3 on 2025-09-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0003_exam_e_max_score_exam_e_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="e_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="exam",
            name="e_status",
            field=models.CharField(default="pending", max_length=255),
        ),
        migrations.AlterField(
            model_name="exam",
            name="e_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
