# Generated by Django 5.2.3 on 2025-09-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "examination_management",
            "0004_alter_exam_e_score_alter_exam_e_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="e_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
