# Generated by Django 5.2.3 on 2025-09-26 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0005_exam_e_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="e_date",
        ),
    ]
