# Generated by Django 5.2.3 on 2025-09-27 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0006_remove_exam_e_date"),
        ("job_management", "0008_alter_applicationstage_s_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="a_id",
        ),
        migrations.CreateModel(
            name="ApplicationExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "a_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_management.application",
                    ),
                ),
                (
                    "e_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination_management.exam",
                    ),
                ),
            ],
            options={
                "db_table": "application_exam",
                "managed": True,
            },
        ),
    ]
