# Generated by Django 5.2.3 on 2025-09-27 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0007_remove_exam_a_id_applicationexam"),
        ("job_management", "0008_alter_applicationstage_s_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="j_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="job_management.job",
            ),
        ),
    ]
