# Generated by Django 5.2.3 on 2025-09-27 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0008_exam_j_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examobservation",
            name="e",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="examination_management.applicationexam",
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="e",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="examination_management.applicationexam",
            ),
        ),
    ]
