# Generated by Django 5.2.3 on 2025-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0009_alter_examobservation_e_alter_examquestion_e"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationexam",
            name="exam_started",
            field=models.BooleanField(default=False),
        ),
    ]
