# Generated by Django 5.2.3 on 2025-09-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0010_applicationexam_exam_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationexam",
            name="last_question",
            field=models.IntegerField(default=0),
        ),
    ]
