# Generated by Django 5.2.3 on 2025-09-28 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0011_applicationexam_last_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examanswer",
            name="a_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="examanswer",
            name="q",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="examination_management.examquestion",
                unique=True,
            ),
        ),
    ]
