# Generated by Django 5.2.3 on 2025-09-28 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0012_alter_examanswer_a_text_alter_examanswer_q"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examanswer",
            name="q",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="examination_management.examquestion",
            ),
        ),
    ]
