# Generated by Django 5.2.3 on 2025-09-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0014_alter_examobservation_e"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examobservation",
            name="o_dressing_code_ok",
            field=models.BooleanField(default=True),
        ),
    ]
