# Generated by Django 5.2.3 on 2025-09-28 22:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0015_alter_examobservation_o_dressing_code_ok"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationexam",
            name="current_time",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ExamNoiseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_level",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("n_timestamp", models.IntegerField(default=0)),
                ("n_sound", models.CharField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "e",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination_management.applicationexam",
                    ),
                ),
            ],
            options={
                "db_table": "exam_noise_history",
                "managed": True,
            },
        ),
    ]
