# Generated by Django 5.2.3 on 2025-09-29 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "examination_management",
            "0016_applicationexam_current_time_examnoisehistory",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewquestion",
            name="i",
        ),
        migrations.RemoveField(
            model_name="interviewobservation",
            name="i",
        ),
        migrations.RemoveField(
            model_name="interviewquestion",
            name="q_choices",
        ),
        migrations.AddField(
            model_name="interviewobservation",
            name="e",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="examination_management.applicationexam",
            ),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="e",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="examination_management.applicationexam",
            ),
        ),
        migrations.AlterField(
            model_name="interviewquestion",
            name="q_correct_answer",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="interviewquestion",
            name="q_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="q",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="examination_management.interviewquestion",
            ),
        ),
        migrations.DeleteModel(
            name="Interview",
        ),
    ]
