# Generated by Django 5.2.3 on 2025-09-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0017_remove_interviewquestion_i_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewquestion",
            name="current_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="interviewresponse",
            name="current_time",
            field=models.IntegerField(default=0),
        ),
    ]
