# Generated by Django 5.2.3 on 2025-09-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0018_interviewquestion_current_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationexam",
            name="exam_ended",
            field=models.BooleanField(default=False),
        ),
    ]
