# Generated by Django 5.2.3 on 2025-10-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0019_applicationexam_exam_ended"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewobservation",
            name="o_clothing",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interviewobservation",
            name="o_communitication_clarity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="interviewobservation",
            name="o_dressing_code_ok",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="interviewobservation",
            name="o_face_expressions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interviewobservation",
            name="o_gestures_detected",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interviewobservation",
            name="o_professionalism_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="interviewobservation",
            name="o_punctuality_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
