# Generated by Django 5.2.3 on 2025-10-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination_management", "0020_interviewobservation_o_clothing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewobservation",
            name="e",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="examination_management.applicationexam",
            ),
        ),
    ]
