# Generated by Django 5.2.3 on 2025-07-03 10:26

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company_management", "0007_alter_companyuser_u_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=255)),
                (
                    "f_url",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="f_url"
                    ),
                ),
                ("f_type", models.CharField(max_length=255)),
                ("f_size", models.CharField(max_length=255)),
                ("f_uploaded_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("f_category", models.TextField()),
                (
                    "c_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company_management.company",
                    ),
                ),
                (
                    "u_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "file",
                "managed": True,
            },
        ),
    ]
