# Generated by Django 5.2.3 on 2025-07-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="f_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
