# Generated by Django 5.2.3 on 2025-07-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_management", "0002_file_f_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="f_format",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="f_resource_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
