# Generated by Django 5.2.3 on 2025-07-03 13:07

import django.utils.timezone
import file_management.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_management", "0003_file_f_format_file_f_resource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="f_path",
            field=models.FileField(
                blank=True,
                null=True,
                storage=file_management.storage.LocalMediaStorage,
                upload_to="cv/",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="file",
            name="f_uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="file",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
