# Generated by Django 5.2.3 on 2025-07-02 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("c_type", models.CharField(blank=True, max_length=255, null=True)),
                ("c_industry", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "c_reg_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("c_address", models.IntegerField(blank=True, null=True)),
                ("c_website", models.CharField(blank=True, max_length=255, null=True)),
                ("c_logo", models.CharField(blank=True, max_length=255, null=True)),
                ("c_email", models.CharField(blank=True, max_length=255, null=True)),
                ("c_phone", models.CharField(blank=True, max_length=255, null=True)),
                ("c_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "company",
                "managed": True,
            },
        ),
    ]
