# Generated by Django 5.2.3 on 2025-07-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
