# Generated by Django 5.2.3 on 2025-07-02 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_management", "0004_companyuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
