# Generated by Django 5.2.3 on 2025-07-02 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_management", "0006_alter_companyuser_u_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyuser",
            name="u_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="company_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
