# Generated by Django 5.2.3 on 2025-09-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_management", "0007_alter_companyuser_u_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="c_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
