# Generated by Django 5.2.3 on 2025-07-03 21:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company_management", "0007_alter_companyuser_u_id"),
        ("file_management", "0004_file_f_path_alter_file_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("j_title", models.CharField(max_length=255)),
                ("j_description", models.TextField(blank=True, null=True)),
                ("j_requirements", models.TextField(blank=True, null=True)),
                ("j_location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "j_employement_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "j_salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "j_salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("j_deadline", models.DateTimeField()),
                ("j_status", models.CharField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "c_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="company_management.company",
                    ),
                ),
                (
                    "j_attachments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="job_attachments",
                        to="file_management.file",
                    ),
                ),
                (
                    "u_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "job",
                "managed": True,
            },
        ),
    ]
