# Generated by Django 5.2.3 on 2025-07-06 13:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_management", "0004_file_f_path_alter_file_created_at_and_more"),
        ("job_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u_id", models.IntegerField()),
                ("j_id", models.IntegerField()),
                ("status", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "a_cover_letter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_letter",
                        to="file_management.file",
                    ),
                ),
            ],
            options={
                "db_table": "application",
                "managed": True,
            },
        ),
    ]
