# Generated by Django 5.2.3 on 2025-09-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_management", "0003_alter_application_j_id_alter_application_u_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="a_cover_letter_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
