# Generated by Django 5.2.3 on 2025-09-25 21:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_management", "0004_application_a_cover_letter_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_name", models.CharField(max_length=255)),
                ("s_started_at", models.DateTimeField(blank=True, null=True)),
                ("s_ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "a_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_stages",
                        to="job_management.application",
                    ),
                ),
            ],
            options={
                "db_table": "application_stage",
                "managed": True,
            },
        ),
    ]
