# Generated by Django 5.2.3 on 2025-09-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_management", "0005_applicationstage"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationstage",
            name="s_completed",
            field=models.BooleanField(default=False),
        ),
    ]
