# Generated by Django 5.2.3 on 2025-09-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_management", "0006_applicationstage_s_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationstage",
            name="s_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
