# Generated by Django 5.2.3 on 2025-09-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_management", "0007_applicationstage_s_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationstage",
            name="s_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="applicationstage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("s_completed", False)),
                fields=("a_id", "s_name"),
                name="unique_active_stage_per_application",
            ),
        ),
    ]
