# Generated by Django 5.2.3 on 2025-07-02 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("u_first_name", models.CharField(max_length=255)),
                ("u_middle_name", models.CharField(max_length=255)),
                ("u_last_name", models.CharField(max_length=255)),
                (
                    "u_role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("recruiter", "Recruiter"),
                            ("admin", "Admin"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("u_is_active", models.BooleanField(default=True)),
                ("u_dob", models.DateField()),
                ("u_gender", models.CharField(max_length=10)),
                ("u_email", models.CharField(max_length=255, unique=True)),
                ("u_phone", models.CharField(max_length=20)),
                ("u_profile_picture", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("has_company", models.BooleanField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "user",
                "managed": True,
            },
        ),
        # migrations.CreateModel(
        #     name="ActivityLog",
        #     fields=[
        #         (
        #             "id",
        #             models.BigAutoField(
        #                 auto_created=True,
        #                 primary_key=True,
        #                 serialize=False,
        #                 verbose_name="ID",
        #             ),
        #         ),
        #         ("a_action", models.TextField()),
        #         ("a_metadata", models.TextField()),
        #         ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
        #         ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
        #         (
        #             "u_id",
        #             models.ForeignKey(
        #                 on_delete=django.db.models.deletion.DO_NOTHING,
        #                 related_name="activity_user",
        #                 to=settings.AUTH_USER_MODEL,
        #             ),
        #         ),
        #     ],
        #     options={
        #         "db_table": "activity_log",
        #         "managed": True,
        #     },
        # ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_action", models.TextField()),
                ("a_ip_address", models.CharField(max_length=255)),
                ("a_user_agent", models.CharField(max_length=255)),
                ("a_metadata", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "u_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="audit_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "managed": True,
            },
        ),
        # migrations.CreateModel(
        #     name="Notification",
        #     fields=[
        #         (
        #             "id",
        #             models.BigAutoField(
        #                 auto_created=True,
        #                 primary_key=True,
        #                 serialize=False,
        #                 verbose_name="ID",
        #             ),
        #         ),
        #         ("n_message", models.TextField()),
        #         ("n_type", models.CharField(max_length=255)),
        #         ("n_is_read", models.BooleanField()),
        #         ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
        #         ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
        #         (
        #             "u_id",
        #             models.ForeignKey(
        #                 on_delete=django.db.models.deletion.DO_NOTHING,
        #                 related_name="notification_user",
        #                 to=settings.AUTH_USER_MODEL,
        #             ),
        #         ),
        #     ],
        #     options={
        #         "db_table": "notification",
        #         "managed": True,
        #     },
        # ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_picture", models.IntegerField(blank=True, null=True)),
                ("p_cover_picture", models.IntegerField(blank=True, null=True)),
                ("a_id", models.IntegerField()),
                (
                    "p_martial_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("p_hobbies", models.TextField(blank=True, null=True)),
                ("p_languages", models.TextField(blank=True, null=True)),
                ("p_bio", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "u_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profile_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profile",
                "managed": True,
            },
        ),
    ]
