# Generated by Django 5.2.3 on 2025-07-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_management", "0001_initial"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="p_cover_picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="profile_cover_picture",
                to="file_management.file",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="p_picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="profile_picture",
                to="file_management.file",
            ),
        ),
    ]
