# Generated by Django 5.2.3 on 2025-07-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0002_alter_profile_p_cover_picture_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="u_profile_picture",
        ),
        migrations.AddField(
            model_name="user",
            name="u_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_profile",
                to="user_management.profile",
            ),
        ),
    ]
