# Generated by Django 5.2.3 on 2025-07-03 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0003_remove_user_u_profile_picture_user_u_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="u_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profile",
                to="user_management.profile",
            ),
        ),
    ]
