# Generated by Django 5.2.3 on 2025-07-03 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_management", "0003_file_f_format_file_f_resource_type"),
        ("user_management", "0004_alter_user_u_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="p_cover_picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_cover_picture",
                to="file_management.file",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="p_picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_picture",
                to="file_management.file",
            ),
        ),
    ]
