# Generated by Django 5.2.3 on 2025-07-04 15:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_management", "0007_alter_companyuser_u_id"),
        ("user_management", "0006_cv"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_country", models.CharField(max_length=255)),
                (
                    "a_province_state",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("a_address_line1", models.TextField()),
                ("a_address_line2", models.TextField(blank=True, null=True)),
                ("a_city", models.CharField(max_length=255)),
                (
                    "a_postal_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "c_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="address_company",
                        to="company_management.company",
                    ),
                ),
                (
                    "u_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="address_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "address",
                "managed": True,
            },
        ),
    ]
