# Generated by Django 5.2.3 on 2025-09-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0007_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="parsed_data",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
