# Generated by Django 5.2.3 on 2025-09-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0008_cv_parsed_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="parsed_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
